### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "qwer1@qwe.com",
  "password": "asdfg"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/3

### Find all users with a given email
GET http://localhost:3000/auth?email=qwer@qwe.com

### Delete user with a given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "aaa@aaa.com"
}